"""Create institutions, physical accounts, and ledger tables.

Revision ID: 0003_physical_accounts_ledger
Revises: 0002_add_totp_fields
Create Date: 2026-09-30 17:09:09.884751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003_physical_accounts_ledger"
down_revision: str | None = "0002_add_totp_fields"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrades the database schema by creating institutions, accounts, and ledger tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institution",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("logo_url", sa.String(length=255), nullable=True),
        sa.Column("parent_institution_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["parent_institution_id"], ["institution.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_institution_name"), "institution", ["name"], unique=True)
    op.create_index(
        op.f("ix_institution_parent_institution_id"), "institution", ["parent_institution_id"], unique=False
    )
    op.create_table(
        "transaction_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("is_reversal", sa.Boolean(), nullable=False),
        sa.Column("reversed_by_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["reversed_by_id"], ["transaction_event.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "physical_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "tax_wrapper",
            sa.Enum("NONE", "ISA", "SIPP", "GIA", name="taxwrapper", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("currency", sa.Enum("GBP", "USD", "EUR", "PHP", name="currency", native_enum=False), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("access_delay_days", sa.Integer(), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("access_delay_days >= 0", name="ck_physical_account_delay_non_negative"),
        sa.CheckConstraint("interest_rate >= 0.0000", name="ck_physical_account_interest_non_negative"),
        sa.ForeignKeyConstraint(["institution_id"], ["institution.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_physical_account_institution_id"), "physical_account", ["institution_id"], unique=False)
    op.create_table(
        "ledger_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("physical_account_id", sa.UUID(), nullable=False),
        sa.Column("virtual_account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.Enum("GBP", "USD", "EUR", "PHP", name="currency", native_enum=False), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["physical_account_id"], ["physical_account.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transaction_event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ledger_entry_transaction_id"), "ledger_entry", ["transaction_id"], unique=False)
    op.create_index("ix_ledger_physical_currency", "ledger_entry", ["physical_account_id", "currency"], unique=False)
    op.create_index("ix_ledger_physical_user", "ledger_entry", ["physical_account_id", "user_id"], unique=False)
    op.create_index("ix_ledger_user_virtual", "ledger_entry", ["user_id", "virtual_account_id"], unique=False)
    op.create_index("ix_ledger_virtual_currency", "ledger_entry", ["virtual_account_id", "currency"], unique=False)
    op.create_table(
        "physical_account_share",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("physical_account_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "CO_OWNER", "ALLOCATOR", name="accountrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["physical_account_id"], ["physical_account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "physical_account_id", name="uq_user_physical_account_share"),
    )
    op.create_index(
        op.f("ix_physical_account_share_physical_account_id"),
        "physical_account_share",
        ["physical_account_id"],
        unique=False,
    )
    op.create_index(op.f("ix_physical_account_share_user_id"), "physical_account_share", ["user_id"], unique=False)
    op.create_table(
        "reconciliation_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("physical_account_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("calculated_drift", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["physical_account_id"], ["physical_account.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_event_physical_account_id"),
        "reconciliation_event",
        ["physical_account_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrades the database schema by dropping institutions, accounts, and ledger tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reconciliation_event_physical_account_id"), table_name="reconciliation_event")
    op.drop_table("reconciliation_event")
    op.drop_index(op.f("ix_physical_account_share_user_id"), table_name="physical_account_share")
    op.drop_index(op.f("ix_physical_account_share_physical_account_id"), table_name="physical_account_share")
    op.drop_table("physical_account_share")
    op.drop_index("ix_ledger_virtual_currency", table_name="ledger_entry")
    op.drop_index("ix_ledger_user_virtual", table_name="ledger_entry")
    op.drop_index("ix_ledger_physical_user", table_name="ledger_entry")
    op.drop_index("ix_ledger_physical_currency", table_name="ledger_entry")
    op.drop_index(op.f("ix_ledger_entry_transaction_id"), table_name="ledger_entry")
    op.drop_table("ledger_entry")
    op.drop_index(op.f("ix_physical_account_institution_id"), table_name="physical_account")
    op.drop_table("physical_account")
    op.drop_table("transaction_event")
    op.drop_index(op.f("ix_institution_parent_institution_id"), table_name="institution")
    op.drop_index(op.f("ix_institution_name"), table_name="institution")
    op.drop_table("institution")
    # ### end Alembic commands ###
